services:
  mongodb:
    container_name: database
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
